### ISSUE TITLE
[Discovery.KubernetesAPI] The discovery module failed to retrive the correct pod list in Azure

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/Akka.Management#313]
Kubernetes client returned a list of all of the pods instead of filtering it to the correct label selector.
The call to `ListNamespacedPodWithHttpMessagesAsync` supposed to pass a label selector to the Kubernetes resource HTTP API and the server is supposed to pass a filtered pod list back to the client but in Azure, the whole pod list is returned, seemingly unfinltered.

There are only 2 containers that satisfies the criteria, but instead the whole pod list is returned:
```
akka.tcp://ClusterSys@10.100.44.22:2557/system/bootstrapCoordinator[0]
      [2021-11-25 19:52:46Z]: Located service members based on: [Lookup(cluster.apimanagementtcp)]: [ResolvedTarget(10.100.44.1910.100.44.19), ResolvedTarget(10.100.44.9310.100.44.93), ResolvedTarget(10.100.44.5410.100.44.54), ResolvedTarget(10.100.44.12810.100.44.128), ResolvedTarget(10.100.44.2510.100.44.25), ResolvedTarget(10.100.44.14010.100.44.140), ResolvedTarget(10.100.44.14510.100.44.145), ResolvedTarget(10.100.44.14610.100.44.146), ResolvedTarget(10.100.44.10710.100.44.107), ResolvedTarget(10.100.44.105855810.100.44.105), ResolvedTarget(10.100.44.22855810.100.44.22), ResolvedTarget(10.100.44.13010.100.44.130), ResolvedTarget(10.100.44.6010.100.44.60), ResolvedTarget(10.100.44.3410.100.44.34), ResolvedTarget(10.100.44.11110.100.44.111), ResolvedTarget(10.100.44.8410.100.44.84), ResolvedTarget(10.100.44.1110.100.44.11)], filtered to [10.100.44.19:0, 10.100.44.93:0, 10.100.44.54:0, 10.100.44.128:0, 10.100.44.25:0, 10.100.44.140:0, 10.100.44.145:0, 10.100.44.146:0, 10.100.44.107:0, 10.100.44.105:8558, 10.100.44.22:8558, 10.100.44.130:0, 10.100.44.60:0, 10.100.44.34:0, 10.100.44.111:0, 10.100.44.84:0, 10.100.44.11:0]
```

Possible causes:
- [x] Discovery is not using the correct k8s namespace (Eliminated)
- [x] Discovery is not using the correct k8s label selector (Eliminated)
- [x] Discovery was misconfigured (Eliminated)
- [x] AKS Kubernetes API server label selector implementation is faulty (Eliminated)

**Comment by Arkatufus** [comment]
This is the k8s yaml:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cluster-api
  labels:
    app: cluster.api
spec:
  serviceName: cluster-api
  replicas: 2
  selector:
    matchLabels:
      app: cluster.api
      aadpodidbinding: azure-access
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cluster.api
        aadpodidbinding: azure-access
    spec:
      containers:
        - name: cluster-api
          image: [REDACTED]
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
            - name: akka
              containerPort: 2557
            - name: akka-management
              containerPort: 8558
            - name: pbm
              containerPort: 9110
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{.Values.environment}}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          readinessProbe:
            tcpSocket:
              port: 2557
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 120
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 30
      terminationGracePeriodSeconds: 60
      serviceAccountName: cluster-api-serviceaccount
```

**Comment by Arkatufus** [comment]
This is the management and discovery HOCON:
```conf
akka {
    management {
        http.port = 8558
        http.hostname = ""
        cluster.bootstrap {
            new-cluster-enabled = true
            contact-point-discovery {
                discovery-method = akka.discovery
                port-name = management
                effective-name = cluster.api
                contact-with-all-contact-points = true
                required-contact-point-nr = 2
                stable-margin = 5s
            }
        }
    }
    discovery {
        method = kubernetes-api
        kubernetes-api {
            class = "Akka.Discovery.KubernetesApi.KubernetesApiServiceDiscovery, Akka.Discovery.KubernetesApi"
            pod-namespace = bootstrapcluster
        }
    }
}
```

**Comment by Arkatufus** [comment]
The default label selector is "app={0}" where "{0}" is replaced by `akka.management.cluster.bootstrap.contact-point-discovery.effective-name`.
The final label selector is "app=cluster.api", which is correct

**Comment by Arkatufus** [comment]
Port name is checked using `Contains`, so the mismatch between the declared port name inside the yaml and the configuration is not the problem.

`"akka-management".Contains("management")` still returns true.

**Comment by Arkatufus** [comment]
The log file confirms this:
```
(akka://ClusterSys)[0] [2021-11-25 19:52:45Z]: Querying for pods with label selector: [app=cluster.api]. Namespace: [bootstrapcluster]. Port: [management]
```

This log is emitted just before we're performing the pod list operation, using all the parameters that are being passed into the Kubernetes client.
https://github.com/akkadotnet/Akka.Management/blob/dev/src/discovery/kubernetes/Akka.Discovery.KubernetesApi/KubernetesApiServiceDiscovery.cs#L85-L99
```c#
if(_log.IsInfoEnabled)
    _log.Info("Querying for pods with label selector: [{0}]. Namespace: [{1}]. Port: [{2}]",
        labelSelector, PodNamespace, lookup.PortName);

var cts = new CancellationTokenSource(resolveTimeout);
V1PodList podList;
try
{
    var result = await _client.ListNamespacedPodWithHttpMessagesAsync(
            namespaceParameter: PodNamespace,
            labelSelector: labelSelector,
            cancellationToken: cts.Token)
        .ConfigureAwait(false);
    podList = result.Body;
}
```

As you can see, labelSelector and PodNamespace never got mutated between the log code and the operation invocation, so we are doing the correct call of:
```
await _client.ListNamespacedPodWithHttpMessagesAsync(
    namespaceParameter: "bootstrapcluster",
    labelSelector: "app=cluster.api")
```

**Comment by Arkatufus** [comment]
The only thing I can think of is that the Kubernetes API inside AKS is flawed and isn't handling the label selector filter correctly, but this needs actual testing in AKS itself.

**Comment by Arkatufus** [comment]
Tested in AKS, works just fine.

**Comment by Arkatufus** [comment]
Note that in AKS, you will need to setup RBAC in kubernetes to let the pods to read pods statuses from the API server. 
A minimum RBAC yaml setting would look something like this:
```yaml
#
# Create a role, `pod-reader`, that can list pods and
# bind the default service account in the namespace
# that the binding is deployed to to that role.
#

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
  # Uses the default service account.
  # Consider creating a dedicated service account to run your
  # Akka Cluster services and binding the role to that one.
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
```
